{-
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
-}
import EulerUtil
--t :: Integral a => a -> Integer
t n = n * (n+1) `div` 2
p n = n * (3 * n - 1) `div` 2
h n = n * (2 * n - 1)

{-
A number t is hexagonal if the solution to this equation is an integer.
2n^2 - n - t = 0

n = -1 +/- (sqrt(1 - 4*2*t) / 4)

And it is pentagonal if the solution to this equation is an integer.

(3/2)n^2 - (1/2)n - t = 0
-}

posQuad a b c = let (r, r') = quadratic a b c
                in filter (>=0) [r, r']

intQuad a b c = filter isInt $ posQuad a b c

pentQuad tv = intQuad (1.5) (-0.5) (-tv)
hexQuad tv = intQuad 2 (-1) (-tv)

isHex = not . null . hexQuad . fromIntegral
isPent = not . null . pentQuad . fromIntegral

answer = head $ filter isHex $ filter isPent $ map t [286..]
